---
# tasks file for icu

- name: Check current version of ICU
  shell: /usr/local/bin/icu-config --version
  register: icu_config_version
  changed_when: False
  ignore_errors: Tru

- name: debug
  debug:
    msg: "{{ icu_config_version }}"

# - name: check ICU version


# - name: update ICU
#   shell: |
#     curl -sS -o /tmp/icu.tar.gz -L http://download.icu-project.org/files/icu4c/59.1/icu4c-59_1-src.tgz
#     tar -zxf /tmp/icu.tar.gz -C /tmp
#     cd /tmp/icu/source
#     ./configure --prefix=/usr/local
#     make
#     make install
#   become: true